### ISSUE TITLE
Example yaml for "Define you own tileset"  needs extra items. 

### ISSUE THREAD

**Issue by craigphicks** [openmaptiles/openmaptiles-tools#26]
In the section of README.md, "Define your own tileset", these items need to be added to the `openmaptiles.yaml` file in order for `generate-tm2source` not to throw an error.

```
  pixel_scale: 256
  defaults:
    srs: +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over
    datasource:
      srid: 900913

```

`language: ...` however is not necessary.
