### ISSUE TITLE
Use local openmaptiles-tools repo for openmaptiles (Docker)

### ISSUE THREAD

**Issue by Falke-Design** [openmaptiles/openmaptiles-tools#361]
#### Connect local `openmaptiles-tools`
The service `openmaptiles-tools` needs to be changed in [`docker-compose.yml`](https://github.com/openmaptiles/openmaptiles/blob/master/docker-compose.yml#L30) in `openmaptiles`.
Replace `image` with `build`
```
  openmaptiles-tools:
    image: "openmaptiles/openmaptiles-tools:${TOOLS_VERSION}"
    env_file: .env
```
with
```
  openmaptiles-tools:
    #image: "openmaptiles/openmaptiles-tools:${TOOLS_VERSION}" #comment
    build:
      context: YOUR_PATH_TO/openmaptiles-tools
      dockerfile: Dockerfile
    env_file: .env
```
Now it uses the local path for the docker image.

#### Generate new docker image after changes:
For every change in `openmaptiles-tools` the docker image needs to be generated new:
For this remove the old docker image:
```
# list all docker images:
docker images

# search for the openmaptiles-tools image and get the `IMAGE ID`

# Remove the docker image
docker rmi IMAGE_ID
```

or simply use:
```
docker rmi $(docker images | grep openmaptiles-tools) #maybe there is a better command for this
```

And then you can simply call your `openmaptiles`-make-script again and the docker image will be generated automatically again.
For example: `make import-osm`

------

I'm a newbe in openmaptiles and in docker so I had some trouble to find out how I can manage this. Because of that I created this "issue" to document it for other peoples. Maybe this is not the cleanest or best way but it a working solution. If someone has a better solution please let me know.

To the Maintainers: Maybe some of you want to add this to the Readme (with a better english spelling) or you can simply close this issue.
