### ISSUE TITLE
Changed IMPOSM Repo makes problems with `make import-sql`

### ISSUE THREAD

**Issue by Falke-Design** [openmaptiles/openmaptiles-tools#363]
With the newest versions (from Github) of openmaptiles and openmaptiles-tools I get following error while calling `make import-sql`:

> psql:/sql/parallel/transportation__transportation_name.sql:232: ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification

The problem part:
```
ALTER TABLE osm_route_member ADD COLUMN IF NOT EXISTS concurrency_index int;

INSERT INTO osm_route_member (id, concurrency_index)
  SELECT
    id,
    ROW_NUMBER() over (PARTITION BY member ORDER BY network_type, network, LENGTH(ref), ref) AS concurrency_index
  FROM osm_route_member
  ON CONFLICT (id) DO UPDATE SET concurrency_index = EXCLUDED.concurrency_index;
```

The sql file:
[transportation__transportation_name_error.sql.txt](https://github.com/openmaptiles/openmaptiles/files/7070921/transportation__transportation_name_error.sql.txt)

The problem comes with the commit 4211019a where in the Dockerfile the IMPOSM Repo is changed from a custom branch / fork to the offical one.

## Steps to reproduce:
Get the repos:
```
git clone https://github.com/openmaptiles/openmaptiles.git
git clone https://github.com/openmaptiles/openmaptiles-tools.git
```

Edit docker-compose.yml in `openmaptiles` to use the local build of openmaptiles-tools (more infos in: #361):
```
  openmaptiles-tools:
    #image: "openmaptiles/openmaptiles-tools:${TOOLS_VERSION}" #comment
    build:
      context: YOUR_PATH_TO/openmaptiles-tools
      dockerfile: Dockerfile
    env_file: .env
```

Call in `openmaptiles`:
```
make
make start-db
make import-data
make download area=liechtenstein
make import-osm
make import-borders
make import-wikidata
make import-sql <-- throws the error
```
